package com.luisovando.app.domain.models;

import java.util.Objects;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Pets")
public class Pet {
	private UUID uuid = UUID.randomUUID();

	@Id
	public String id;
	public String name;
	public String species;
	public String breed;

	public Pet() {
		// Default constructor is required by AWS DynamoDB SDK
	}

	public Pet(String id, String name, String species, String breed) {
		this.id = id;
		this.name = name;
		this.species = species;
		this.breed = breed;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute
	public String getSpecies() {
		return species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	@DynamoDBAttribute
	public String getBreed() {
		return breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		final Pet pet = (Pet) o;
		return Objects.equals(uuid, pet.uuid);
	}

	@Override
	public int hashCode() {
		return Objects.hash(uuid);
	}
}
